import { config } from 'dotenv';
config();

export const ADMIN_TEST_PUBLIC_KEY =
  process.env.ADMIN_PUBLIC_KEY ||
  'GDETU6WELGHH6T3RBYXPHBNQAYCGPPNGUDUEEIYGPEWU3JESG7IQ4VLL';
export const ADMIN_TEST_PRIVATE_KEY =
  process.env.ADMIN_PRIVATE_KEY ||
  'SBTB75TFCEJQLIPISSBC2ZDGTQNBCBYFVB36PLONWSBMTPOQT5V7RUHB';
export const FRIENDBOT_URL = 'https://friendbot.stellar.org';
